In [97]:
import json
import re
import os
import pandas as pd
from collections import Counter
import sys
sys.path.append(os.path.dirname(os.getcwd()))
from Path import *
from Utils import *
from spacy.lang.en import English
from Services.skills import SkillsExtractor
from nltk.tokenize import word_tokenize
from nltk import pos_tag

In [2]:
os.chdir('C:\\Users\\SOUMEN\\Projects\\JobPostings')

In [3]:
nlp = English()
skill_extractor = SkillsExtractor(nlp)

In [6]:
linkedid_data_path = 'Data/linked_in.json'
linkedid_parsed_data_path = 'Data/linked_in_parsed.json'

In [7]:
jobs_parsed = read_json(linkedid_parsed_data_path)
jobs = read_json(linkedid_data_path)

In [73]:
job_positions = [jb["job_position"] for jb in jobs_parsed]

jobs_counter = Counter(job_positions)

df_jobs = pd.DataFrame.from_dict(jobs_counter, orient='index').reset_index().sort_values(by=0, ascending=False)
df_jobs.rename(columns = {'index': 'position', 0: 'count'}, inplace=True)
df_jobs.reset_index(drop=True,inplace=True)

In [74]:
df_jobs

                                              position  count
0                                       Data Scientist    109
1                                    Software Engineer     90
2                                Senior Data Scientist     42
3                                     Python Developer     26
4                            Machine Learning Engineer     25
..                                                 ...    ...
418  TransOrg Analytics - Lead Data Scientist - Pre...      1
419                  Lead - Data Scientist - Analytics      1
420           Senior Manager- Lead Data Scientist, D&A      1
421                 Data Scientist - Model Development      1
422  Software Development Engineer, Prime Tech Core...      1

[423 rows x 2 columns]

In [10]:
[job['job_sections'][4] for job in jobs_parsed]

['10 hours ago',
 '9 hours ago',
 'Full-time · Mid-Senior level',
 '9 hours ago',
 '13 hours ago',
 '146 applicants',
 '10 hours ago',
 '30 applicants',
 '6 applicants',
 '12 hours ago',
 '10 hours ago',
 '4 days ago',
 '4 applicants',
 '14 hours ago',
 '8 hours ago',
 '13 hours ago',
 '3 days ago',
 '8 hours ago',
 '1 applicant',
 '6 applicants',
 '1 hour ago',
 '3 days ago',
 '9 applicants',
 '3 days ago',
 '104 applicants',
 '4 applicants',
 '3 days ago',
 '2 weeks ago',
 '13 hours ago',
 '3 days ago',
 '2 weeks ago',
 '2 weeks ago',
 '23 applicants',
 '3 days ago',
 '12 hours ago',
 '1 hour ago',
 '3 hours ago',
 '11 applicants',
 '1 week ago',
 '4 days ago',
 '1 week ago',
 '61 applicants',
 '62 applicants',
 '18 applicants',
 '1 week ago',
 '75 applicants',
 '12 hours ago',
 '1 hour ago',
 '2 days ago',
 '3 weeks ago',
 '14 applicants',
 '1 week ago',
 '1 week ago',
 '2 weeks ago',
 '4 days ago',
 '120 applicants',
 '2 weeks ago',
 '160 applicants',
 '8 hours ago',
 '3 weeks ago',
 '4 days ago',
 '6 days ago',
 '38 applicants',
 '3 weeks ago',
 'Over 200 applicants',
 '1 week ago',
 '63 applicants',
 '3 days ago',
 '62 applicants',
 '53 applicants',
 '2 weeks ago',
 'Over 200 applicants',
 '12 hours ago',
 '127 applicants',
 '7 hours ago',
 '62 applicants',
 '82 applicants',
 '50 applicants',
 '1 week ago',
 '1 week ago',
 '2 weeks ago',
 '2 applicants',
 '3 days ago',
 '1 hour ago',
 '3 days ago',
 '1 week ago',
 '1 week ago',
 '6 days ago',
 '1 hour ago',
 '1 week ago',
 '2 weeks ago',
 '8 hours ago',
 'Full-time · Entry level',
 '2 days ago',
 '3 days ago',
 '121 applicants',
 '154 applicants',
 '14 applicants',
 '1 week ago',
 '1 week ago',
 '1 week ago',
 '1 week ago',
 '2 weeks ago',
 '4 days ago',
 '1 week ago',
 '159 applicants',
 '1 week ago',
 '2 applicants',
 '1 week ago',
 '1 week ago',
 '3 days ago',
 '195 applicants',
 '8 hours ago',
 '4 days ago',
 '1 week ago',
 '2 weeks ago',
 '2 weeks ago',
 '3 days ago',
 '6 days ago',
 '1 week ago',
 'Over 200 applicants',
 '2 weeks ago',
 '10 applicants',
 '3 days ago',
 '18 applicants',
 'Over 200 applicants',
 '2 weeks ago',
 '2 weeks ago',
 '2 weeks ago',
 '1 week ago',
 '1 week ago',
 '1 week ago',
 '1 week ago',
 '2 days ago',
 '3 weeks ago',
 '1 applicant',
 '4 days ago',
 '1 week ago',
 '1 applicant',
 '3 days ago',
 '71 applicants',
 '1 week ago',
 '1 week ago',
 '3 weeks ago',
 '2 weeks ago',
 '13 hours ago',
 '1 week ago',
 '2 weeks ago',
 '45 applicants',
 '6 days ago',
 '2 weeks ago',
 '1 week ago',
 '2 weeks ago',
 '3 days ago',
 '62 applicants',
 '1 week ago',
 '2 weeks ago',
 '3 weeks ago',
 '3 weeks ago',
 '1 week ago',
 '70 applicants',
 '3 days ago',
 '6 days ago',
 '3 days ago',
 '76 applicants',
 '1 week ago',
 '1 week ago',
 '2 weeks ago',
 '6 days ago',
 '2 weeks ago',
 'Over 200 applicants',
 '1 week ago',
 '2 weeks ago',
 'Over 200 applicants',
 '1 week ago',
 '2 weeks ago',
 '1 week ago',
 '6 days ago',
 '3 weeks ago',
 '123 applicants',
 '4 days ago',
 '1 week ago',
 '38 applicants',
 '1 week ago',
 '1 week ago',
 '2 applicants',
 '1 week ago',
 '2 weeks ago',
 '1 week ago',
 '1 week ago',
 '1 week ago',
 '4 days ago',
 '83 applicants',
 '1 week ago',
 '33 applicants',
 '2 weeks ago',
 '1 week ago',
 '3 weeks ago',
 'Full-time · Entry level',
 '1 week ago',
 '1 week ago',
 '1 week ago',
 '1 week ago',
 '1 week ago',
 '65 applicants',
 '46 applicants',
 '3 weeks ago',
 '67 applicants',
 '3 days ago',
 '86 applicants',
 '1 week ago',
 '2 weeks ago',
 '12 applicants',
 '3 days ago',
 '2 weeks ago',
 '1 week ago',
 '1 week ago',
 '2 weeks ago',
 '39 applicants',
 '2 weeks ago',
 '2 weeks ago',
 '2 weeks ago',
 '3 weeks ago',
 '2 weeks ago',
 '2 days ago',
 '6 days ago',
 '1 week ago',
 '2 weeks ago',
 '2 weeks ago',
 '2 weeks ago',
 '93 applicants',
 '1 week ago',
 '2 weeks ago',
 '1 week ago',
 '2 weeks ago',
 '42 applicants',
 '13 hours ago',
 '2 weeks ago',
 '41 applicants',
 '6 days ago',
 '4 applicants',
 '2 weeks ago',
 '1 week ago',
 '3 weeks ago',
 '1 week ago',
 '3 weeks ago',
 '2 days ago',
 '2 weeks ago',
 '1 week ago',
 '6 days ago',
 '2 weeks ago',
 '1 week ago',
 '34 applicants',
 '1 week ago',
 '6 days ago',
 '3 weeks ago',
 '3 weeks ago',
 '1 week ago',
 '3 days ago',
 '1 week ago',
 '2 weeks ago',
 '1 week ago',
 '3 days ago',
 '6 days ago',
 '2 weeks ago',
 '2 weeks ago',
 '72 applicants',
 '6 applicants',
 '2 weeks ago',
 '2 weeks ago',
 '3 weeks ago',
 '23 applicants',
 '3 weeks ago',
 '80 applicants',
 '1 week ago',
 '2 weeks ago',
 '3 weeks ago',
 '3 weeks ago',
 '4 days ago',
 '1 week ago',
 '5 days ago',
 '1 week ago',
 '3 weeks ago',
 '3 weeks ago',
 '3 days ago',
 '1 week ago',
 '2 weeks ago',
 '6 days ago',
 '1 applicant',
 '2 weeks ago',
 '2 weeks ago',
 '3 days ago',
 '3 days ago',
 '3 weeks ago',
 '2 weeks ago',
 '38 applicants',
 '2 weeks ago',
 '1 week ago',
 '1 week ago',
 '6 days ago',
 '2 weeks ago',
 '5 days ago',
 '2 applicants',
 '1 week ago',
 '19 applicants',
 '3 weeks ago',
 '2 weeks ago',
 '30 applicants',
 '13 hours ago',
 '13 hours ago',
 '2 weeks ago',
 '1 week ago',
 '120 applicants',
 '154 applicants',
 '3 days ago',
 '13 hours ago',
 '1 week ago',
 '2 weeks ago',
 '28 applicants',
 '13 hours ago',
 '1 week ago',
 '115 applicants',
 '3 weeks ago',
 '3 weeks ago',
 '34 applicants',
 '2 weeks ago',
 '4 applicants',
 '29 applicants',
 '27 applicants',
 '5 days ago',
 '3 weeks ago',
 '2 weeks ago',
 '13 hours ago',
 '4 days ago',
 '2 weeks ago',
 '1 week ago',
 '1 week ago',
 '24 applicants',
 '6 applicants',
 '12 applicants',
 '1 week ago',
 '7 hours ago',
 '2 weeks ago',
 '2 weeks ago',
 '1 week ago',
 '1 week ago',
 '3 weeks ago',
 '13 hours ago',
 '13 hours ago',
 '2 weeks ago',
 '19 applicants',
 '1 week ago',
 '42 applicants',
 '1 week ago',
 '65 applicants',
 '9 hours ago',
 '7 hours ago',
 '2 weeks ago',
 '13 hours ago',
 '2 applicants',
 '13 hours ago',
 '6 days ago',
 '1 week ago',
 '3 weeks ago',
 '5 applicants',
 '2 weeks ago',
 '25 applicants',
 '2 weeks ago',
 '3 days ago',
 '2 weeks ago',
 '3 weeks ago',
 '2 weeks ago',
 '1 week ago',
 '15 applicants',
 '2 weeks ago',
 '19 applicants',
 '1 week ago',
 '57 applicants',
 '18 applicants',
 '2 weeks ago',
 '31 applicants',
 '3 days ago',
 'Full-time · Associate',
 '42 applicants',
 '2 applicants',
 '2 weeks ago',
 '11 hours ago',
 '3 weeks ago',
 '1 week ago',
 '3 weeks ago',
 '1 week ago',
 '1 week ago',
 '3 weeks ago',
 '6 days ago',
 '14 applicants',
 '2 weeks ago',
 'Full-time · Associate',
 '3 weeks ago',
 '1 week ago',
 '48 applicants',
 '43 applicants',
 '2 weeks ago',
 '1 week ago',
 '1 week ago',
 '4 days ago',
 '1 week ago',
 '2 weeks ago',
 '2 weeks ago',
 '1 week ago',
 '1 week ago',
 '1 week ago',
 '1 week ago',
 '2 weeks ago',
 '2 weeks ago',
 '2 weeks ago',
 '14 applicants',
 '3 applicants',
 '6 days ago',
 'Over 200 applicants',
 '5 minutes ago',
 '2 weeks ago',
 '1 applicant',
 '15 hours ago',
 '13 applicants',
 '2 weeks ago',
 '1 week ago',
 '1 week ago',
 '2 weeks ago',
 '2 weeks ago',
 '21 applicants',
 '3 days ago',
 '1 week ago',
 '13 hours ago',
 '13 hours ago',
 '4 days ago',
 '2 weeks ago',
 '3 days ago',
 '1 week ago',
 '2 weeks ago',
 '3 applicants',
 '3 days ago',
 '3 weeks ago',
 '11 hours ago',
 '2 weeks ago',
 '2 weeks ago',
 '1 week ago',
 '1 week ago',
 '3 days ago',
 '1 week ago',
 '13 hours ago',
 '39 applicants',
 '1 week ago',
 '180 applicants',
 '2 weeks ago',
 '102 applicants',
 'Full-time · Associate',
 '3 days ago',
 '10 hours ago',
 '1 week ago',
 '3 weeks ago',
 '1 week ago',
 '7 hours ago',
 '14 hours ago',
 '3 days ago',
 '1 week ago',
 '2 applicants',
 '3 days ago',
 '2 weeks ago',
 '4 days ago',
 '8 hours ago',
 '2 weeks ago',
 '3 days ago',
 '1 week ago',
 '3 days ago',
 '58 applicants',
 '39 applicants',
 '46 applicants',
 '2 weeks ago',
 'Over 200 applicants',
 '8 hours ago',
 '4 days ago',
 '2 weeks ago',
 '12 applicants',
 '3 weeks ago',
 '1 week ago',
 '2 weeks ago',
 '1 week ago',
 '2 hours ago',
 '12 applicants',
 '10 applicants',
 '8 applicants',
 '13 hours ago',
 '14 hours ago',
 '1 week ago',
 '13 hours ago',
 '13 hours ago',
 '4 days ago',
 '51 applicants',
 '2 weeks ago',
 '5 applicants',
 '59 applicants',
 '45 applicants',
 '149 applicants',
 '3 weeks ago',
 '13 hours ago',
 '4 days ago',
 '1 week ago',
 '63 applicants',
 '48 applicants',
 '1 week ago',
 '21 applicants',
 '7 applicants',
 '1 week ago',
 '10 hours ago',
 '1 week ago',
 '1 week ago',
 '6 hours ago',
 '36 applicants',
 '3 days ago',
 '2 weeks ago',
 '3 weeks ago',
 '1 week ago',
 '47 applicants',
 '93 applicants',
 '1 week ago',
 '1 week ago',
 '68 applicants',
 '1 week ago',
 '3 weeks ago',
 '8 hours ago',
 '4 days ago',
 '3 days ago',
 '3 weeks ago',
 '4 days ago',
 '27 applicants',
 '10 hours ago',
 '1 week ago',
 '20 applicants',
 '42 applicants',
 '3 weeks ago',
 '2 weeks ago',
 '66 applicants',
 '1 week ago',
 '1 hour ago',
 '2 hours ago',
 '70 applicants',
 '9 applicants',
 '3 days ago',
 '1 week ago',
 '3 days ago',
 '36 applicants',
 '3 weeks ago',
 '3 applicants',
 '1 hour ago',
 '3 days ago',
 '2 weeks ago',
 '4 days ago',
 '2 weeks ago',
 '30 applicants',
 '2 weeks ago',
 '29 applicants',
 '27 applicants',
 '1 day ago',
 '6 days ago',
 '183 applicants',
 '12 hours ago',
 'Full-time · Entry level',
 '19 applicants',
 '4 days ago',
 '4 days ago',
 '2 applicants',
 '3 weeks ago',
 '5 days ago',
 '4 days ago',
 '6 hours ago',
 '3 days ago',
 '10 applicants',
 '55 minutes ago',
 '2 applicants',
 'Full-time · Mid-Senior level',
 '1 applicant',
 '13 hours ago',
 '3 days ago',
 'Full-time · Entry level',
 '11 hours ago',
 '1 day ago',
 '18 applicants',
 '64 applicants',
 '1 week ago',
 '2 days ago',
 '1 day ago',
 '9 applicants',
 '21 applicants',
 '22 applicants',
 '171 applicants',
 '2 weeks ago',
 '3 weeks ago',
 '164 applicants',
 '19 hours ago',
 '13 hours ago',
 '5 applicants',
 'Over 200 applicants',
 '26 applicants',
 '3 days ago',
 '3 days ago',
 '3 days ago',
 '36 applicants',
 '3 weeks ago',
 '86 applicants',
 '3 applicants',
 '16 applicants',
 '2 days ago',
 '1 day ago',
 '3 weeks ago',
 '2 weeks ago',
 '137 applicants',
 'Full-time · Mid-Senior level',
 '4 days ago',
 '1 week ago',
 '4 hours ago',
 '22 applicants',
 '17 applicants',
 '1 week ago',
 '12 hours ago',
 '3 days ago',
 '2 weeks ago',
 '134 applicants',
 '10 applicants',
 '10 applicants',
 '2 weeks ago',
 '8 applicants',
 '4 days ago',
 '6 days ago',
 '15 hours ago',
 '4 days ago',
 '36 applicants',
 '1 week ago',
 '1 applicant',
 '41 applicants',
 'Over 200 applicants',
 '62 applicants',
 '15 applicants',
 '6 applicants',
 '45 applicants',
 '3 days ago',
 'Full-time · Mid-Senior level',
 '19 applicants',
 '4 hours ago',
 '4 hours ago',
 '24 applicants',
 '51 applicants',
 '4 days ago',
 '49 applicants',
 'Full-time · Mid-Senior level',
 '2 applicants',
 '15 applicants',
 '69 applicants',
 '7 hours ago',
 '86 applicants',
 '65 applicants',
 '23 applicants',
 '42 applicants',
 '63 applicants',
 '10 hours ago',
 '1 day ago',
 '4 days ago',
 '4 days ago',
 '81 applicants',
 '3 weeks ago',
 '1 week ago',
 '22 applicants',
 '4 days ago',
 '12 hours ago',
 '16 applicants',
 '10 hours ago',
 '54 applicants',
 '89 applicants',
 '9 applicants',
 '19 applicants',
 '15 applicants',
 '7 applicants',
 '4 hours ago',
 '23 applicants',
 '4 applicants',
 '3 days ago',
 '3 days ago',
 '3 weeks ago',
 '3 applicants',
 'Full-time · Entry level',
 '4 days ago',
 '14 applicants',
 '1 week ago',
 '8 applicants',
 '37 applicants',
 '113 applicants',
 '6 days ago',
 '6 days ago',
 '2 days ago',
 '5 days ago',
 '3 weeks ago',
 '4 days ago',
 '4 days ago',
 '4 days ago',
 '1 week ago',
 '7 hours ago',
 '1 week ago',
 '2 weeks ago',
 '2 weeks ago',
 '161 applicants',
 '2 applicants',
 '2 applicants',
 '1 applicant',
 '3 days ago',
 '16 hours ago',
 '9 applicants',
 '16 applicants',
 '3 days ago',
 '13 hours ago',
 '12 hours ago',
 '11 hours ago',
 '7 applicants',
 '2 weeks ago',
 '2 weeks ago',
 '3 weeks ago',
 '3 days ago',
 '4 days ago',
 '4 days ago',
 '4 days ago',
 'Full-time · Mid-Senior level',
 '4 days ago',
 '3 days ago',
 '3 days ago',
 '3 days ago',
 '11 applicants',
 '7 hours ago',
 '15 hours ago',
 '1 week ago',
 '4 days ago',
 '27 applicants',
 '1 week ago',
 '1 week ago',
 '1 week ago',
 '9 hours ago',
 '82 applicants',
 '7 applicants',
 '3 days ago',
 '1 week ago',
 '3 weeks ago',
 '4 days ago',
 '14 hours ago',
 '7 applicants',
 '5 hours ago',
 '1 week ago',
 '1 week ago',
 '2 weeks ago',
 '1 applicant',
 '2 applicants',
 '6 days ago',
 'Full-time · Entry level',
 '1 week ago',
 '41 applicants',
 '5 days ago',
 '4 days ago',
 '6 days ago',
 '13 hours ago',
 '12 hours ago',
 '3 weeks ago',
 'Over 200 applicants',
 '1 week ago',
 '116 applicants',
 '50 applicants',
 '6 days ago',
 '2 days ago',
 '6 days ago',
 '1 week ago',
 '4 days ago',
 '6 days ago',
 '13 hours ago',
 '12 hours ago',
 '3 weeks ago',
 'Over 200 applicants',
 '1 week ago',
 '116 applicants',
 '50 applicants',
 '6 days ago',
 '2 days ago',
 '6 days ago',
 '1 week ago',
 '26 applicants',
 '1 week ago',
 '1 week ago',
 '11 hours ago',
 '10 hours ago',
 '6 applicants',
 '1 week ago',
 '1 week ago',
 '11 hours ago',
 '13 hours ago',
 '3 hours ago',
 '10 hours ago',
 '62 applicants',
 '6 hours ago',
 '12 applicants',
 '38 applicants',
 '2 hours ago',
 '3 weeks ago',
 '3 days ago',
 '1 week ago',
 '14 hours ago',
 '72 applicants',
 '4 hours ago',
 '20 applicants',
 '30 applicants',
 '2 days ago',
 '27 applicants',
 '3 days ago',
 '58 minutes ago',
 '6 days ago',
 '1 week ago',
 'Full-time',
 '6 hours ago',
 '1 hour ago',
 '33 applicants',
 '3 days ago',
 '3 weeks ago',
 '3 weeks ago',
 '2 weeks ago',
 '1 week ago',
 '64 applicants',
 '1 week ago',
 '10 hours ago',
 '22 applicants',
 '2 applicants',
 '5 applicants',
 '1 applicant',
 '7 hours ago',
 'Full-time · Mid-Senior level',
 '13 hours ago',
 '1 week ago',
 '1 applicant',
 '3 applicants',
 '4 hours ago',
 '5 days ago',
 '1 week ago',
 '2 days ago',
 '4 hours ago',
 '33 minutes ago',
 '28 applicants',
 '3 days ago',
 '3 weeks ago',
 '1 week ago',
 '22 applicants',
 '16 applicants',
 '4 hours ago',
 '1 week ago',
 '12 hours ago',
 '1 week ago',
 '7 applicants',
 '10 hours ago',
 '13 hours ago',
 '1 week ago',
 '14 hours ago',
 '10 hours ago',
 '13 hours ago',
 '34 applicants',
 '2 weeks ago',
 '6 applicants',
 '1 week ago',
 '16 applicants',
 '8 applicants',
 '1 week ago',
 '11 hours ago',
 '19 hours ago',
 '19 hours ago',
 '3 weeks ago',
 '34 applicants',
 '2 weeks ago',
 '6 applicants',
 '1 week ago',
 '16 applicants',
 '8 applicants',
 '1 week ago',
 '11 hours ago',
 '19 hours ago',
 '19 hours ago',
 '3 weeks ago',
 '8 applicants',
 '5 days ago',
 '4 applicants',
 '13 applicants',
 '8 hours ago',
 '4 applicants',
 '4 applicants',
 '4 applicants',
 '33 applicants',
 '8 applicants',
 '26 applicants',
 '8 applicants',
 '3 days ago',
 '43 applicants',
 '1 week ago',
 '4 hours ago',
 '15 applicants',
 '4 days ago',
 '10 hours ago',
 '5 days ago',
 '17 applicants',
 '6 applicants',
 '6 applicants',
 '14 hours ago',
 '3 weeks ago',
 '19 hours ago',
 '19 hours ago',
 '1 week ago',
 '14 hours ago',
 '5 hours ago',
 '14 hours ago',
 '4 days ago',
 '15 applicants',
 '4 days ago',
 '1 week ago',
 '14 hours ago',
 '1 applicant',
 '28 applicants',
 '3 days ago',
 '28 applicants',
 '30 applicants',
 '2 applicants',
 '2 weeks ago',
 '1 applicant',
 '1 applicant',
 '2 weeks ago',
 '1 week ago',
 '4 days ago',
 '8 applicants',
 '4 applicants',
 '16 hours ago',
 '11 hours ago',
 '5 hours ago',
 '13 hours ago',
 '8 hours ago',
 '4 days ago',
 '6 days ago',
 '14 hours ago',
 '1 applicant',
 '20 applicants',
 '1 week ago',
 '1 week ago',
 '1 applicant',
 '1 week ago',
 '1 hour ago',
 '14 applicants',
 '4 days ago',
 '1 applicant',
 '87 applicants',
 '3 days ago',
 '1 week ago',
 '1 day ago',
 '2 hours ago',
 '11 hours ago',
 '1 week ago',
 '3 days ago',
 '4 applicants',
 '1 week ago',
 '1 week ago',
 '4 days ago',
 '6 days ago',
 '17 applicants',
 '23 applicants',
 '22 applicants',
 '1 week ago',
 '1 week ago',
 '54 applicants',
 'Full-time',
 '1 applicant']

In [34]:
[pos_tag(bl) for bl in jobs_parsed[2]['job_sections'][:10]]

LookupError:
**********************************************************************
  Resource averaged_perceptron_tagger not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('averaged_perceptron_tagger')

  For more information see: https://www.nltk.org/data.html

  Attempted to load taggers/averaged_perceptron_tagger/averaged_perceptron_tagger.pickle

  Searched in:
    - 'C:\\Users\\SOUMEN/nltk_data'
    - 'C:\\Users\\SOUMEN\\anaconda3\\nltk_data'
    - 'C:\\Users\\SOUMEN\\anaconda3\\share\\nltk_data'
    - 'C:\\Users\\SOUMEN\\anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\SOUMEN\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

In [13]:
[jd for jd in jobs_parsed[2]['job_sections'] if 'phd' in jd.lower()]

[]

In [79]:
jobs_parsed[2]

{'job_position': 'Data Scientist',
 'company': 'Syneos Health Commercial Solutions',
 'job_sections': ['Data Scientist',
  'Syneos Health Commercial Solutions',
  'Bengaluru, Karnataka, India',
  '2 hours ago',
  'Full-time · Mid-Senior level',
  '10,001+ employees · Pharmaceutical Manufacturing',
  'See recent hiring trends for Syneos Health Commercial Solutions. Try Premium for free',
  'Your skills are a strong match for this jobYour skills are a strong match for this job',
  'Apply',
  'Save',
  'Save Data Scientist at Syneos Health Commercial Solutions',
  'Share',
  'Show more options',
  'Data Scientist',
  'Syneos Health Commercial Solutions',
  'Bengaluru, Karnataka, India',
  'Apply',
  'Save',
  'Save Data Scientist at Syneos Health Commercial Solutions',
  'Show more options',
  'Overview',
  'Do you have a noticeable passion for results?',
  'You’re bold, empathetic, and very resourceful, especially when results are at stake. You have what it takes: a competitive drive coupled with the exceptional ability to communicate the science behind our client’s products and build lasting business relationships. Such talent and passion make you the right fit for this Data Scientist with Syneos Health.',
  'As a Data Scientist at Syneos Health you Design, develop and program methods, processes, and systems to consolidate and analyze unstructured, diverse “big data” sources to generate actionable insights and solutions for client services and product enhancement. Interact with product and service teams to identify questions and issues for data analysis and experiments. Develop and codes software programs, algorithms and automated processes to cleanse, integrate and evaluate large datasets from multiple disparate sources. Identify meaningful insights from large data and metadata sources; interpret and communicates insights and findings from analysis and experiments to product, service, and business managers.',
  'Responsibilities',
  'Analyze structured and unstructured data sets using quantitative techniques to solve a wide range of business problems and address client needs Integrate and manage multiple healthcare-centric data sources for the purposes of deriving quantitative insights, developing machine learning-based models, discovering and ranking features, and statistical analysis (e.g. hypothesis testing). Use best industry practices to develop model validation and QA pipelines Efficiently and clearly, communicate complex statistical concepts and project goals to internal and external stakeholders Gather performance metrics and project requirements from business partners and clients to develop forecasting models, classifiers, and statistically based solutions Develop and deliver reports and presentations that clearly explain quantitative products and strategies to a wide range of internal and external audiencesExplore data using programming skills to interpret large data sets from a variety of sources including finance, sales, and healthcare claims',
  'Job Requirements',
  'Along with demonstrated initiative, uncompromised integrity and a results-oriented mindset, the ideal candidate has:',
  'Bachelor’s degree required; Graduate degree in computer science or statistics (highly preferred) Minimum 3+ years of work experience.Must possess strong research, analytical and numerical skills and the ability to think critically and creatively on engagements. Demonstrated attention to detail required Experience in research and data analysis (e.g., organization of sources, data processing, analysis, and quality checking accuracy for pre-defined problems) Strong presentation skills required Effective and professional communication skills (verbal, interpersonal, and written) required Exceptional collaboration skills and the ability to work in cross-functional teams Excellent time-management skills Knowledge of advanced visualization and analytical tools such as Tableau, and Power BI (Preferred).Background in data science and one or more of the following: statistics, computer science, business intelligence, library science, or equivalent experience. Capable of independently designing, conducting, and analyzing research projects and client projects. Capable of independently transforming, cleaning, and loading large data sets. Experience with digital/programmatic advertising, performance analytics, web scraping, and\u202fNLP (a plus). Proficient in using and implementing ML algorithms. (factor analysis, structural equation modeling, Bayesian statistics, PCA, machine learning approaches (e.g., Regression, Classification, clustering, Regularization algorithms (e.g., Elastic net)). Proficient with the following technologies: SQL, Python.',
  'At Syneos Health, we believe in providing an environment and culture in which our people can thrive, develop and advance. We reward and recognize our people by providing valuable benefits and a quality of life balance.',
  'Why Syneos Health? Join a game-changing global company that is reinventing the way therapies are developed and commercialized. Here, you’re empowered to exceed your sales goals with the autonomy you need to over deliver. We’re dedicated to creating better, smarter, faster ways to get biopharmaceutical therapies to patients. Syneos Health has launched more sales teams in the last 5 years across all major Therapeutic Areas than the top 25 pharma companies combined. By joining Syneos Health, you’ll be connected to our multitude of career paths and pipeline of employment opportunities.',
  'WORK HERE MATTERS EVERYWHERE | How will you accelerate pharmaceutical sales?',
  'Syneos Health is an affirmative action/equal opportunity employer (Minorities/Females/Vet/Disabled)']}

In [81]:
skills_extracted = dict(skill_extractor.extract_skills(jobs[1]))
skills = []
for key in skills_extracted.keys():
    skill_dict = dict(skills_extracted[key])
    for match in skill_dict["matches"]:
        skill_dict.update({"skill": key})
        skill_dict.update(match)
    del skill_dict['matches']
    skills.append(skill_dict)
dfs = pd.DataFrame(skills)

In [90]:
skills_extracted['business']

defaultdict(list,
            {'matches': [{'start': 1585,
               'end': 1593,
               'label': 'SKILL',
               'text': 'business'}],
             'displayName': 'Business',
             'shortDescription': 'Business is the activity of making one\'s living or making money by producing or buying and selling products (such as goods and services). Simply put, it is "any activity or enterprise entered into for profit. It does not mean it is a company, a corporation, partnership, or have any such formal organization, but it can range from a street peddler to General Motors."',
             'longDescription': '',
             'sources': [{'name': 'Microsoft Academic Graph',
               'url': 'https://academic.microsoft.com/api/entity/144133560?entityType=7'}]})

In [96]:
jobs[1][1575:]

'o address business challenges.Presentation of results in a clear and concise manner.Collaborate with engineering and product development teams.\nQualifications\nProven experience as a Data Scientist or Data Analyst.Deep understanding in statistics, regressions, and mixed model.Experience using business intelligence tools (e.g. Tableau or PowerBI) to create visualizations.Experience in data mining techniques.Experience with Excel and Visual Basic.Knowledge of R, SQL and Python is a plus.Knowledge of machine learning techniques and applications is a plus.Excellent communication and presentation skills.\n \n\n \n\n\n\n\n\n\n\n\n\n\n\n \n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'

In [88]:
jobs_parsed[1]['job_sections']

['Data Scientist',
 'Hire Digital',
 'Bengaluru, Karnataka, India',
 'Remote',
 '9 hours ago',
 '173 applicants',
 'Part-time · Mid-Senior level',
 '51-200 employees · Advertising Services',
 'See how you compare to 173 applicants. Try Premium for free',
 'Your skills are a strong match for this jobYour skills are a strong match for this job',
 'Apply',
 'Save',
 'Save Data Scientist at Hire Digital',
 'Share',
 'Show more options',
 'Data Scientist',
 'Hire Digital',
 'Bengaluru, Karnataka, India',
 'Remote',
 'Apply',
 'Save',
 'Save Data Scientist at Hire Digital',
 'Show more options',
 'A pharmaceutical client is seeking a Data Scientist whose primary responsibility will to perform statistical analysis, build a sales forecasting model and and create an internal tool to enable sales teams to import sales data and visualize sales forecasts.',
 'Responsibilities',
 'Review and analyze sales data for patterns and trends.Identify the best forecast model based on the data provided.Build an Excel-based tool to ingest data, and generate outputs for visualization.Validate and test model against several scenarios and edge cases.Recommend strategies and solutions to enhance forecasting to address business challenges.Presentation of results in a clear and concise manner.Collaborate with engineering and product development teams.',
 'Qualifications',
 'Proven experience as a Data Scientist or Data Analyst.Deep understanding in statistics, regressions, and mixed model.Experience using business intelligence tools (e.g. Tableau or PowerBI) to create visualizations.Experience in data mining techniques.Experience with Excel and Visual Basic.Knowledge of R, SQL and Python is a plus.Knowledge of machine learning techniques and applications is a plus.Excellent communication and presentation skills.']

In [85]:
dfs

,displayName,shortDescription,longDescription,sources,skill,start,end,label,text
0,Advertising,Advertising is a marketing communication that ...,,"[{'name': 'Microsoft Academic Graph', 'url': '...",advertising,332,343,SKILL,Advertising
1,Visualization,Visualization or visualisation (see spelling d...,,"[{'name': 'Microsoft Academic Graph', 'url': '...",visualization,1437,1450,SKILL,visualization
2,Business,Business is the activity of making one's livin...,,"[{'name': 'Microsoft Academic Graph', 'url': '...",business,1585,1593,SKILL,business
3,Engineering,"Engineering is the application of knowledge, t...",,"[{'name': 'Microsoft Academic Graph', 'url': '...",engineering,1676,1687,SKILL,engineering
4,Mixed model,A mixed model is a statistical model containin...,,"[{'name': 'Microsoft Academic Graph', 'url': '...",mixed-model,1839,1850,SKILL,mixed model
5,Business Intelligence,,,"[{'name': 'Microsoft Academic Graph', 'url': '...",business-intelligence,1868,1889,SKILL,business intelligence
6,Tableau,Tableau helps people see and understand data.,Tableau can help anyone see and understand the...,"[{'name': 'Stackshare Skills', 'url': 'http://...",tableau,1902,1909,SKILL,Tableau
7,Data mining,Data mining is the process of discovering patt...,,"[{'name': 'Microsoft Academic Graph', 'url': '...",data-mining,1961,1972,SKILL,data mining
8,Visual Basic,"Modern, high-level, multi-paradigm, general-pu...",Visual Basic is derived from BASIC and enables...,"[{'name': 'Stackshare Skills', 'url': 'http://...",visual-basic,2010,2022,SKILL,Visual Basic
9,R,R is a free programming language and software ...,R is a free programming language and software ...,"[{'name': 'Github Topics', 'url': 'https://www...",r,2036,2037,SKILL,R
10,SQL,"SQL is a standard language for storing, retrie...",SQL stands for structured query language. It u...,"[{'name': 'Github Topics', 'url': 'https://www...",sql,2039,2042,SKILL,SQL
11,Python,Python is a dynamically typed programming lang...,Python is a dynamically typed programming lang...,"[{'name': 'Github Topics', 'url': 'https://www...",python,2047,2053,SKILL,Python
12,Machine learning,Machine learning is a way of modeling and inte...,Machine learning is the practice of teaching a...,"[{'name': 'Github Topics', 'url': 'https://www...",machine-learning,2077,2093,SKILL,machine learning

In [98]:
jobs = read_json(LINKEDIN_PARSED_JOBS_DATA_PATH)
langs = read_json(PROGRAMMING_LANGUAGES_PATH)
skills_position = sum([jb["skills"] for jb in jobs], [])
langs_position = [sp for sp in skills_position if sp in langs]
skills_position = [sp for sp in skills_position if sp not in langs]

# skills_counter = Counter(skills_position)
# df_skills = pd.DataFrame.from_dict(skills_counter, orient='index').reset_index().sort_values(by=0, ascending=False)
# df_skills.rename(columns={'index': 'Skill', 0: 'Jobs count'}, inplace=True)
# df_skills.reset_index(drop=True, inplace=True)

# langs_counter = Counter(langs_position)
# df_langs = pd.DataFrame.from_dict(langs_counter, orient='index').reset_index().sort_values(by=0, ascending=False)
# df_langs.rename(columns={'index': 'Programming Languages', 0: 'Jobs count'}, inplace=True)
# df_langs.reset_index(drop=True, inplace=True)

In [111]:
skill_values = []
all_skills = skill_extractor._get_skills()
for k in all_skills.keys():
    if isinstance(all_skills[k], list):
        skill_values = skill_values + all_skills[k]
    elif isinstance(all_skills[k], dict):
        skill_values.append(all_skills[k])

skill_values = [sv['sources'][0] for sv in skill_values]

In [113]:
df_allskills = pd.DataFrame(skill_values)

In [119]:
df_allskills[df_allskills['displayName'] == 'Tensorflow']

,id,sourceName,displayName,shortDescription,longDescription,url
1810,github.tensorflow,Github Topics,Tensorflow,TensorFlow is an open source software library ...,TensorFlow is an open source library that was ...,https://www.github.com/topics/tensorflow